language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:
- xctool clean build -project CEMKit-Swift.xcodeproj -scheme CEMKit-Swift
- xcodebuild [DEFAULT_OPTIONS] CODE_SIGNING_REQUIRED=NO
notifications:
 email: true